trigger:
- main

pool: Default

stages:
- stage: InstallTerraform
  displayName: Install Terraform
  jobs:
  - job: TerraformInstall
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

- stage: TerraformInit
  displayName: Terraform Init
  jobs:
  - job: RunTerraformInit
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'hclsc'
        backendAzureRmStorageAccountName: 'hclstorage1'
        backendAzureRmContainerName: 'hclcontainer'
        backendAzureRmKey: 'hcl.statefile'

- stage: TerraformValidate
  displayName: Terraform Validate
  jobs:
  - job: RunTerraformValidate
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'