trigger:
- main

pool: default

stages:

# Stage 1 - Install Terraform
- stage: InstallTerraform
  displayName: Install Terraform
  jobs:
  - job: TerraformInstall
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

# Stage 2 - Terraform Init
- stage: TerraformInit
  displayName: Terraform Init
  jobs:
  - job: RunTerraformInit
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'hclsc'
        backendAzureRmStorageAccountName: 'hclstorage1'
        backendAzureRmContainerName: 'hclcontainer'
        backendAzureRmKey: 'hcl.statefile'

# Stage 3 - Terraform Validate
- stage: TerraformValidate
  displayName: Terraform Validate
  jobs:
  - job: RunTerraformValidate
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'